# Generated by Django 5.2 on 2025-04-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='butterflies',
            old_name='breed',
            new_name='species',
        ),
        migrations.AlterField(
            model_name='butterflies',
            name='description',
            field=models.TextField(),
        ),
    ]
