# Generated by Django 5.2 on 2025-04-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_breed_butterflies_species_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='butterflies',
            name='age',
        ),
        migrations.AddField(
            model_name='butterflies',
            name='wingspan',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
