# Generated by Django 5.2 on 2025-04-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='butterfly',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
